#page title
page_title                                : Travel Sort Expense                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6737707322                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : au                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/au/app/travel-sort-expense/id6737707322                                         # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Travel Sort Expense                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Sort and track your shared travel expenses with ease! An app designed specifically designed for shared cards.      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Claren So                                
your_link                                 :                     
your_city                                 : Sydney                                
email_address                             : travelsortexpense@gmail.com
linkedin_username                         : 0-sclaren                                     
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : cccsso
youtube_username                          : TravelSortExpense
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :
- title: Expense Sorting
  description: Ability to sort travel expenses by who to save you accounting time on every trip.
  fontawesome_icon_name: filter

- title: Owed Amount Calculations
  description: Automatically calculates who owes what based on who paid for the shared expense.
  fontawesome_icon_name: calculator

- title: Realtime Sync
  description: All expenses and updates sync instantly across devices.
  fontawesome_icon_name: sync

- title: Daily Exchange Rate Updates
  description: Stay accurate with daily refreshed exchange rates for accurate currency conversion.
  fontawesome_icon_name: chart-line

- title: Multi-Currency Support
  description: Handles currency conversion with live exchange rates, perfect for international travel.
  fontawesome_icon_name: money-bill-wave

- title: App Shortcuts Integration
  description: Log ApplePay expenses instantly to the app with App Shortcuts.
  fontawesome_icon_name: bolt

- title: Spending Insights
  description: Visualise top spending categories with interactive bar charts that reveal your spending habits for the trip.
  fontawesome_icon_name: chart-bar

- title: Daily Spend Calendar
  description: Track daily expenses on a calendar with a clear breakdown of who spent what, day by day.
  fontawesome_icon_name: calendar-alt

- title: Invite and Join Trips
  description: Easily join or invite others to shared trips using unique invite codes.
  fontawesome_icon_name: users

# - title: Offline Mode
#   description: Add and view expenses without internet—your data will sync once you're back online.
#   fontawesome_icon_name: wifi-slash

# - title: Photo Receipts
#   description: Snap and attach receipts to each expense entry for easy reference and accountability.
#   fontawesome_icon_name: camera

  # - title                                 : # New Feature Title
  #   description                           : # New Feature Description
  #   fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#f3fff2"

cover_image                               : assets/headerimage.png
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.1

device_color                              : black

body_background_color                     : "#f3fff2"

link_color                                : "#1d9c17"

app_title_color                           : "#f3fff2"
app_price_color                           : "#2F8C28"
app_description_color                     : black

feature_title_color                       : black
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d9c17"
feature_icons_background_color            : "#d7f5d5"

social_icons_foreground_color             : "#1d9c17"
social_icons_background_color             : "#d7f5d5"

footer_text_color                         : "#666666"
footer_background_color                   : "#e5fce3"












####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
